### PR TITLE
replace secp256k1 with bcrypto#secp256k1

### PR DESCRIPTION
**Pull request by faustbrian**
Possibly addresses https://github.com/luniehq/cosmos-keys/issues/13 as I am currently experiencing this issue which makes it impossible to sign transactions with a server-side application.

### CODE REVIEW

**Comment by faboweb** [comment]
Does tis work in the browser?

**Comment by faustbrian** [comment]
I tried it briefly in chrome and had no issues due to `bcrypto` also having browser bindings https://github.com/bcoin-org/bcrypto/blob/master/package.json#L95 but would appreciate someone else testing.

Also, could forks be enabled on CircleCI so that the tests could run?

**Comment by faustbrian** [comment]
There 2 more things that could be done to streamline things a bit.

1. Create a node and browser build to keep things separate.
2. Replace `crypto-js` with `bcrypto` methods to rely only on a single dependency for crypto.

**Comment by Bitcoinera** [comment]
I tested this with couple different networks on the browser and it is working great.

Awesome job @faustbrian !

**Comment by faboweb** [comment]
Doing a release later. Good idea about the steps reduction!

**Comment by faustbrian** [comment]
I generally like to keep browser and node.js builds separated to avoid having dependencies or polyfills included that would be useless for node.js or could potentially even cause issues with making wrong assumptions about the environment.

**Comment by faboweb** [comment]
I published the package

**Comment by faboweb** [comment]
> I generally like to keep browser and node.js builds separated to avoid having dependencies or polyfills included that would be useless for node.js or could potentially even cause issues with making wrong assumptions about the environment and its data types.

good argument. happy about a PR doing though. Rn we are a bit busy with other things.

**Comment by faustbrian** [comment]
> > I generally like to keep browser and node.js builds separated to avoid having dependencies or polyfills included that would be useless for node.js or could potentially even cause issues with making wrong assumptions about the environment and its data types.
> 
> good argument. happy about a PR doing though. Rn we are a bit busy with other things.

Will try to find some time for it in the next days.

**Pull request merged**
